const globalNewsDomains = [
  // International News
  'bbc.com',
  'reuters.com',
  'apnews.com',
  'aljazeera.com',
  'france24.com',
  'dw.com',
  'euronews.com',
  'bloomberg.com',
  'economist.com',
  'ft.com',
  'nytimes.com',
  'wsj.com',
  'theguardian.com',
  'independent.co.uk',
  'time.com',
  'cnn.com',
  'nbcnews.com',
  'abcnews.go.com',
  'cbsnews.com',
  'foxnews.com',
  'usatoday.com',
  'latimes.com',
  'chicagotribune.com',
  'washingtonpost.com',
  'politico.com',
  'thehill.com',
  'axios.com',
  'vox.com',
  'huffpost.com',
  'vice.com',
  'slate.com',
  'salon.com',
  'thedailybeast.com',

  // European News
  'spiegel.de',
  'faz.net',
  'lemonde.fr',
  'lefigaro.fr',
  'corriere.it',
  'repubblica.it',
  'elpais.com',
  'elmundo.es',
  'nrc.nl',
  'volkskrant.nl',
  'dn.se',
  'aftonbladet.se',
  'dr.dk',
  'yle.fi',
  'vg.no',
  'nrk.no',

  // Asian News
  'scmp.com',
  'nikkei.com',
  'asahi.com',
  'yomiuri.co.jp',
  'thehindu.com',
  'hindustantimes.com',
  'timesofindia.indiatimes.com',
  'straitstimes.com',
  'channelnewsasia.com',
  'bangkokpost.com',
  'inquirer.net',
  'thejakartapost.com',

  // Middle Eastern News
  'haaretz.com',
  'jpost.com',
  'timesofisrael.com',
  'arabnews.com',
  'gulfnews.com',
  'khaleejtimes.com',
  'tehrantimes.com',
  'dailystar.com.lb',

  // African News
  'news24.com',
  'mg.co.za',
  'iol.co.za',
  'nation.africa',
  'standardmedia.co.ke',
  'allafrica.com',
  'theeastafrican.co.ke',
  'dailynewsegypt.com',

  // Oceania News
  'abc.net.au',
  'smh.com.au',
  'theaustralian.com.au',
  'nzherald.co.nz',
  'stuff.co.nz',
  'rnz.co.nz',
]

// News Agencies
const newsAgencyDomains = [
  'ap.org',
  'reuters.com',
  'afp.com',
  'dpa.com',
  'efe.com',
  'ansa.it',
  'kyodonews.net',
  'xinhuanet.com',
  'tass.com',
  'prnewswire.com',
  'upi.com',
]

export default [...globalNewsDomains, ...newsAgencyDomains]
