name: Build Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build extension
        run: npm run build:extension

      - name: Zip extension
        run: zip -r shield-extension.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shield-extension
          path: shield-extension.zip
          if-no-files-found: error
